### ISSUE TITLE
Option to only show nil nodes

### ISSUE THREAD

**Issue by DannyBen** [fphilipe/i18n-debug#2]
Not sure if this is still maintained or not, but it would be nice to have an option to show only calls to non existing nodes. Maybe there is a way to do it with overriding the default handler, but I am not sure how to do it based on the instructions in the README (i.e., where should I put the overriding code)

**Comment by fphilipe** [comment]
``` ruby
I18n::Debug.on_lookup = lambda do |key, value|
  logger.debug("Missing key: #{key}") unless value
end
```

Put that somewhere after requiring this gem. In Rails that would be in an initializer. Does that answer your question? :blush:

**Comment by DannyBen** [comment]
Yes, thanks. 

Added a new initializer with this code

```
if defined? I18n::Debug
  I18n::Debug.on_lookup = lambda do |key, result|
    Rails.logger.debug("[i18n-debug] #{key}") unless result
  end
end
```
