### ISSUE TITLE
Version 1.1 not compatible with ruby 2.0 - Module#prepend is private method

### ISSUE THREAD

**Issue by mmrwoods** [fphilipe/i18n-debug#3]
Hi,

Thanks for this gem, which has helped me quickly track down some translation issues with nested attributes :-)

I had to use use version 1.0 with Ruby 2.0 though, because Module#prepend is private in Ruby 2.0. Given Ruby 2.0 is nearing end of life, I doubt it's worth making the code more complicated to support it, but an update to the readme is probably worthwhile.

Mark

**Comment by fphilipe** [comment]
> Thanks for this gem, which has helped me quickly track down some translation issues with nested attributes :-)

Good to hear :blush: 

> I had to use use version 1.0 with Ruby 2.0 though, because Module#prepend is private in Ruby 2.0. Given Ruby 2.0 is nearing end of life, I doubt it's worth making the code more complicated to support it, but an update to the readme is probably worthwhile.

The README already mentioned this, but for _< 2_. I'll change it to _<= 2.0_. Thanks!
